# Generated by Django 3.1.2 on 2021-01-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='category',
        ),
        migrations.AddField(
            model_name='project',
            name='tag',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
