# Generated by Django 3.1.2 on 2021-01-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20210117_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Flooring & Staircase', 'Flooring & Staircase'), ('Carving', 'Carving'), ('Wall Cladding', 'Wall Cladding'), ('Home & Garden Decor', 'Home & Garden Decor'), ('Home Mandir', 'Home Mandir'), ('Inlay', 'Inlay'), ('Qibla & Mimbar', 'Qibla & Mimbar'), ('Jali', 'Jali'), ('Katera & Kabr', 'Katera & Kabr'), ('Railing', 'Railing'), ('Name Plate', 'Name Plate')], max_length=20),
        ),
    ]
